// examples/nuxt/app/pages/tech.vue
<script setup lang="ts">
const inspection = useNuxtApp().$contributions.inspect();
const { data: overview } = await useFetch('/api/demo/overview');

const extensionSelection = computed(() => overview.value?.extensionSelection);
const providerSlots = computed(() => overview.value?.providerSelection?.slots ?? []);
const selectedProviderIds = computed(() =>
  providerSlots.value
    .filter((slot) => slot.state === 'selected')
    .map((slot) => slot.selectedProviderId),
);
const providerCandidateIds = computed(() => [
  ...new Set(providerSlots.value.flatMap((slot) => slot.candidateProviderIds)),
]);
const unfilledProviderCapabilities = computed(() =>
  providerSlots.value.filter((slot) => slot.state === 'unfilled').map((slot) => slot.capabilityId),
);
</script>

<template>
  <main class="page">
    <header class="intro">
      <p>Nuxt integration example</p>
      <h1>Tech monitor</h1>
      <NuxtLink v-if="extensionSelection?.resolvedExtensionIds.includes('shops')" to="/">
        Back
      </NuxtLink>
      <p>Extension profile: {{ extensionSelection?.selectedExtensionIds[0] }}</p>
    </header>

    <pre data-testid="contribution-inspection">{{ JSON.stringify(inspection) }}</pre>
    <section class="grid">
      <article>
        <h2>Resolved extensions</h2>
        <ul class="list">
          <li v-for="id in extensionSelection?.resolvedExtensionIds" :key="id">
            <span>{{ id }}@{{ extensionSelection?.resolvedExtensionVersions?.[id] }}</span>
          </li>
        </ul>
      </article>

      <article>
        <h2>Selected provider</h2>
        <ul class="list">
          <li v-for="id in selectedProviderIds" :key="id">
            <span>{{ id }}</span>
          </li>
        </ul>
      </article>

      <article>
        <h2>Provider candidates</h2>
        <ul class="list">
          <li v-for="id in providerCandidateIds" :key="id">
            <span>{{ id }}</span>
          </li>
        </ul>
      </article>

      <article>
        <h2>Unfilled provider slots</h2>
        <ul class="list">
          <li v-for="id in unfilledProviderCapabilities" :key="id">
            <span>{{ id }}</span>
          </li>
        </ul>
      </article>

      <article>
        <h2>Not injected</h2>
        <ul class="list">
          <li v-for="id in extensionSelection?.notInjectedExtensionIds" :key="id">
            <span>{{ id }}</span>
          </li>
        </ul>
      </article>
    </section>
  </main>
</template>

<style scoped>
.page {
  display: grid;
  gap: 16px;
  max-width: 1120px;
  padding: 32px;
  color: #202124;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
}

h1 {
  margin: 0;
  font-size: 2rem;
}

h2 {
  margin: 0 0 12px;
  font-size: 1rem;
}

.grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(220px, 1fr));
  gap: 12px;
}

article {
  min-width: 0;
  padding: 16px;
  border: 1px solid #dadce0;
  border-radius: 8px;
  background: #ffffff;
}

.note {
  color: #5f6368;
}

.list,
.checks {
  display: grid;
  gap: 8px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.list li {
  overflow-wrap: anywhere;
}

.checks li {
  display: flex;
  justify-content: space-between;
  gap: 12px;
}

.note {
  margin: 0;
  font-size: 0.9rem;
  line-height: 1.45;
}

pre {
  overflow: auto;
  min-height: 96px;
  max-height: 180px;
  margin: 0;
  padding: 10px;
  border-radius: 6px;
  background: #f1f3f4;
  font-size: 0.8rem;
  line-height: 1.45;
}

a {
  color: #0b57d0;
  font-weight: 700;
  text-decoration: none;
}

@media (max-width: 980px) {
  .summary,
  .grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 620px) {
  .page {
    padding: 20px;
  }

  .summary,
  .grid {
    grid-template-columns: 1fr;
  }
}
</style>

// examples/react-runtime/src/routes/tech.tsx
import { contributionRuntime } from '../router';
import { createFileRoute } from '@tanstack/react-router';
import { useMemo, type ReactElement } from 'react';
import { createDemoOverview } from '../demoOverview';

export const Route = createFileRoute('/tech')({
  component: TechMonitor,
});

function TechMonitor(): ReactElement {
  const { capabilityRuntime } = Route.useRouteContext();
  const overview = useMemo(() => createDemoOverview(capabilityRuntime), [capabilityRuntime]);
  const activeProviderIds = contributionRuntime
    .inspect()
    .filter(
      (row) =>
        row.status === 'active' &&
        row.target.owner === 'payments' &&
        row.target.point === 'payment-method',
    )
    .map((row) => row.id);
  const providerCandidateIds = [
    ...new Set(overview.providerSelection.slots.flatMap((slot) => slot.candidateProviderIds)),
  ];
  const unfilledProviderSlots = overview.providerSelection.slots
    .filter((slot) => slot.state === 'unfilled')
    .map((slot) => slot.capabilityId);

  return (
    <main className="page page-wide">
      <header className="intro">
        <p>React integration example</p>
        <h1>Tech monitor</h1>
        {overview.capabilitySelection.resolvedCapabilityIds.includes('shops') && (
          <a href="/">Back</a>
        )}
        <p>Capability profile: {overview.capabilitySelection.selectedCapabilityIds[0]}</p>
      </header>

      <pre data-testid="contribution-inspection">
        {JSON.stringify(contributionRuntime.inspect())}
      </pre>
      <section className="grid">
        <MonitorCard
          title="Resolved capabilities"
          values={overview.capabilitySelection.resolvedCapabilityIds.map(
            (id) => `${id}@${overview.resolvedCapabilityVersions[id]}`,
          )}
        />
        <MonitorCard title="Active provider" values={activeProviderIds} />
        <MonitorCard title="Provider candidates" values={providerCandidateIds} />
        <MonitorCard title="Unfilled provider slots" values={unfilledProviderSlots} />
        <MonitorCard
          title="Not injected"
          values={overview.capabilitySelection.notInjectedCapabilityIds}
        />
      </section>
    </main>
  );
}

function MonitorCard({
  title,
  values,
}: Readonly<{ title: string; values: string[] }>): ReactElement {
  return (
    <article>
      <h2>{title}</h2>
      <ul className="list">
        {values.map((value) => (
          <li key={value}>
            <span>{value}</span>
          </li>
        ))}
      </ul>
    </article>
  );
}
